name: Build & Redeploy

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-22.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build --tag $REPO:latest --tag $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image tagged with commit sha
        run: docker push  $REPO:${GITHUB_SHA::8} 
      - name: Publish Docker image latest
        run: docker push $REPO:latest
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-22.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
      - name: Use Node.js 10.x 
        uses: actions/setup-node@v1 
        with: 
          node-version: 10.x 
      - name: npm install, make test-coverage 
        run: |
          npm install
          make test-coverage 
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.0
        with: 
          github-token: ${{ secrets.MY_TOKEN }}
